package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"unified-commerce/services/cart/models"
)

// FindCartByID is the resolver for the findCartByID field.
func (r *entityResolver) FindCartByID(ctx context.Context, id string) (*models.Cart, error) {
	panic("not implemented: FindCartByID - findCartByID")
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
