// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"unified-commerce/services/cart/models"
)

type AddLineItemInput struct {
	CartID           string  `json:"cartId"`
	ProductID        string  `json:"productId"`
	ProductVariantID *string `json:"productVariantId,omitempty"`
	Quantity         int     `json:"quantity"`
	Price            float64 `json:"price"`
	Name             string  `json:"name"`
	Sku              string  `json:"sku"`
	Properties       *string `json:"properties,omitempty"`
}

type AddressInput struct {
	FirstName  *string  `json:"firstName,omitempty"`
	LastName   *string  `json:"lastName,omitempty"`
	Company    *string  `json:"company,omitempty"`
	Street1    *string  `json:"street1,omitempty"`
	Street2    *string  `json:"street2,omitempty"`
	City       *string  `json:"city,omitempty"`
	State      *string  `json:"state,omitempty"`
	Country    *string  `json:"country,omitempty"`
	PostalCode *string  `json:"postalCode,omitempty"`
	Phone      *string  `json:"phone,omitempty"`
	Latitude   *float64 `json:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty"`
}

type CartFilter struct {
	CustomerID *string            `json:"customerId,omitempty"`
	MerchantID *string            `json:"merchantId,omitempty"`
	Status     *models.CartStatus `json:"status,omitempty"`
	SessionID  *string            `json:"sessionId,omitempty"`
	Limit      *int               `json:"limit,omitempty"`
	Offset     *int               `json:"offset,omitempty"`
}

type CreateCartInput struct {
	SessionID         string  `json:"sessionId"`
	CustomerID        *string `json:"customerId,omitempty"`
	MerchantID        string  `json:"merchantId"`
	Currency          *string `json:"currency,omitempty"`
	CustomerEmail     *string `json:"customerEmail,omitempty"`
	CustomerPhone     *string `json:"customerPhone,omitempty"`
	CustomerFirstName *string `json:"customerFirstName,omitempty"`
	CustomerLastName  *string `json:"customerLastName,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateCartInput struct {
	SessionID         *string              `json:"sessionId,omitempty"`
	CustomerID        *string              `json:"customerId,omitempty"`
	Status            *models.CartStatus   `json:"status,omitempty"`
	Currency          *string              `json:"currency,omitempty"`
	CustomerEmail     *string              `json:"customerEmail,omitempty"`
	CustomerPhone     *string              `json:"customerPhone,omitempty"`
	CustomerFirstName *string              `json:"customerFirstName,omitempty"`
	CustomerLastName  *string              `json:"customerLastName,omitempty"`
	CheckoutStep      *models.CheckoutStep `json:"checkoutStep,omitempty"`
	PaymentMethodID   *string              `json:"paymentMethodId,omitempty"`
	ShippingMethodID  *string              `json:"shippingMethodId,omitempty"`
	Notes             *string              `json:"notes,omitempty"`
	Attributes        *string              `json:"attributes,omitempty"`
}

type UpdateLineItemInput struct {
	Quantity   *int     `json:"quantity,omitempty"`
	Price      *float64 `json:"price,omitempty"`
	Properties *string  `json:"properties,omitempty"`
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
