services:
  - type: web
    name: unified-commerce-identity
    runtime: go
    plan: free
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/identity
    envVars:
      - key: PORT
        value: "8001"
        
  - type: web
    name: unified-commerce-gateway
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: gateway
    envVars:
      - key: PORT
        value: "4000"
        
  - type: pserv
    name: unified-commerce-postgres
    plan: free
    
  - type: redis
    name: unified-commerce-redis
    plan: free
    ipAllowList: []
