services:
services:
  # MongoDB as a Private Service using official MongoDB Docker image
  - type: pserv
    name: unified-commerce-mongodb
    image:
      image: mongo:latest
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        generateValue: true
      - key: MONGO_INITDB_ROOT_PASSWORD
        generateValue: true
    disks:
      - name: mongo-data
        mountPath: /data/db
        sizeGB: 1

  - type: web
    name: unified-commerce-identity
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/identity
    envVars:
      - key: PORT
        value: "8001"
      - key: SERVICE_PORT
        value: "8001"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: unified-commerce-redis
          property: connectionString

  - type: web
    name: unified-commerce-product-catalog
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/product-catalog
    envVars:
      - key: PORT
        value: "8002"
      - key: SERVICE_PORT
        value: "8002"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: MONGO_URL
        fromService:
          type: pserv
          name: unified-commerce-mongodb
          property: internalConnectionString
      - key: MONGO_DATABASE
        value: "product_catalog"
      - key: REDIS_URL
        fromDatabase:
          name: unified-commerce-redis
          property: connectionString

  - type: web
    name: unified-commerce-order
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/order
    envVars:
      - key: PORT
        value: "8003"
      - key: SERVICE_PORT
        value: "8003"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString

  - type: web
    name: unified-commerce-payment
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/payment
    envVars:
      - key: PORT
        value: "8004"
      - key: SERVICE_PORT
        value: "8004"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString

  - type: web
    name: unified-commerce-inventory
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/inventory
    envVars:
      - key: PORT
        value: "8005"
      - key: SERVICE_PORT
        value: "8005"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString

  - type: web
    name: unified-commerce-merchant-account
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/merchant-account
    envVars:
      - key: PORT
        value: "8006"
      - key: SERVICE_PORT
        value: "8006"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString

  - type: web
    name: unified-commerce-cart
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/cart
    envVars:
      - key: PORT
        value: "8007"
      - key: SERVICE_PORT
        value: "8007"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: unified-commerce-redis
          property: connectionString

  - type: web
    name: unified-commerce-promotions
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/promotions
    envVars:
      - key: PORT
        value: "8008"
      - key: SERVICE_PORT
        value: "8008"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: unified-commerce-redis
          property: connectionString

  - type: web
    name: unified-commerce-analytics
    runtime: go
    plan: starter
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    rootDir: services/analytics
    envVars:
      - key: PORT
        value: "8009"
      - key: SERVICE_PORT
        value: "8009"
      - key: DISABLE_TELEMETRY
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: unified-commerce-postgres
          property: connectionString
      - key: MONGO_URL
        fromService:
          type: pserv
          name: unified-commerce-mongodb
          property: internalConnectionString
      - key: MONGO_DATABASE
        value: "analytics"
      - key: REDIS_URL
        fromDatabase:
          name: unified-commerce-redis
          property: connectionString

  - type: web
    name: unified-commerce-gateway
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    rootDir: gateway
    envVars:
      - key: PORT
        value: "4000"
      - key: IDENTITY_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-identity
          property: host
      - key: PRODUCT_CATALOG_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-product-catalog
          property: host
      - key: ORDER_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-order
          property: host
      - key: PAYMENT_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-payment
          property: host
      - key: INVENTORY_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-inventory
          property: host
      - key: MERCHANT_ACCOUNT_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-merchant-account
          property: host
      - key: CART_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-cart
          property: host
      - key: PROMOTIONS_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-promotions
          property: host
      - key: ANALYTICS_SERVICE_URL
        fromService:
          type: web
          name: unified-commerce-analytics
          property: host

databases:
  - name: unified-commerce-postgres
    databaseName: unified_commerce
    user: unified_commerce_user
  - name: unified-commerce-redis
    type: redis