package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"unified-commerce/services/promotions/models"
)

// FindCampaignByID is the resolver for the findCampaignByID field.
func (r *entityResolver) FindCampaignByID(ctx context.Context, id string) (*models.Campaign, error) {
	panic(fmt.Errorf("not implemented: FindCampaignByID - findCampaignByID"))
}

// FindDiscountCodeByID is the resolver for the findDiscountCodeByID field.
func (r *entityResolver) FindDiscountCodeByID(ctx context.Context, id string) (*models.DiscountCode, error) {
	panic(fmt.Errorf("not implemented: FindDiscountCodeByID - findDiscountCodeByID"))
}

// FindPromotionByID is the resolver for the findPromotionByID field.
func (r *entityResolver) FindPromotionByID(ctx context.Context, id string) (*models.Promotion, error) {
	panic(fmt.Errorf("not implemented: FindPromotionByID - findPromotionByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
