// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

// Input types for GraphQL operations
type AddressInput struct {
	FirstName  *string  `json:"firstName,omitempty"`
	LastName   *string  `json:"lastName,omitempty"`
	Company    *string  `json:"company,omitempty"`
	Street1    *string  `json:"street1,omitempty"`
	Street2    *string  `json:"street2,omitempty"`
	City       *string  `json:"city,omitempty"`
	State      *string  `json:"state,omitempty"`
	Country    *string  `json:"country,omitempty"`
	PostalCode *string  `json:"postalCode,omitempty"`
	Phone      *string  `json:"phone,omitempty"`
	Latitude   *float64 `json:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty"`
}

type CreatePaymentInput struct {
	OrderID         *string       `json:"orderId,omitempty"`
	CustomerID      *string       `json:"customerId,omitempty"`
	MerchantID      string        `json:"merchantId"`
	Amount          float64       `json:"amount"`
	Currency        string        `json:"currency"`
	PaymentMethodID string        `json:"paymentMethodId"`
	BillingAddress  *AddressInput `json:"billingAddress,omitempty"`
	Description     *string       `json:"description,omitempty"`
	Metadata        *string       `json:"metadata,omitempty"`
}

type CreatePaymentMethodInput struct {
	CustomerID     string            `json:"customerId"`
	MerchantID     string            `json:"merchantId"`
	Type           PaymentMethodType `json:"type"`
	Token          string            `json:"token"`
	IsDefault      *bool             `json:"isDefault,omitempty"`
	BillingAddress *AddressInput     `json:"billingAddress,omitempty"`
	Metadata       *string           `json:"metadata,omitempty"`
}

type RefundPaymentInput struct {
	Amount      float64 `json:"amount"`
	Reason      *string `json:"reason,omitempty"`
	Description *string `json:"description,omitempty"`
	Metadata    *string `json:"metadata,omitempty"`
}

type UpdatePaymentMethodInput struct {
	IsDefault      *bool         `json:"isDefault,omitempty"`
	BillingAddress *AddressInput `json:"billingAddress,omitempty"`
	Metadata       *string       `json:"metadata,omitempty"`
}

type PaymentFilter struct {
	OrderID    *string        `json:"orderId,omitempty"`
	CustomerID *string        `json:"customerId,omitempty"`
	MerchantID *string        `json:"merchantId,omitempty"`
	Status     *PaymentStatus `json:"status,omitempty"`
	Gateway    *string        `json:"gateway,omitempty"`
	Limit      *int           `json:"limit,omitempty"`
	Offset     *int           `json:"offset,omitempty"`
}

// Federation entities for external references
type Order struct {
	ID string `json:"id"`
}

func (Order) IsEntity() {}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}

// Empty mutation and query types for GraphQL schema
type Mutation struct{}
type Query struct{}