package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"unified-commerce/services/payment/models"
)

// FindAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode is the resolver for the findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode field.
func (r *entityResolver) FindAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(ctx context.Context, firstName *string, lastName *string, street1 *string, street2 *string, city *string, state *string, country *string, postalCode *string) (*models.Address, error) {
	panic(fmt.Errorf("not implemented: FindAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode - findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode"))
}

// FindPaymentByID is the resolver for the findPaymentByID field.
func (r *entityResolver) FindPaymentByID(ctx context.Context, id string) (*models.Payment, error) {
	// For now, return nil - this would normally query the payment service
	r.Logger.WithField("payment_id", id).Info("Finding payment by ID")
	return nil, fmt.Errorf("not implemented: FindPaymentByID - findPaymentByID")
}

// FindPaymentMethodByID is the resolver for the findPaymentMethodByID field.
func (r *entityResolver) FindPaymentMethodByID(ctx context.Context, id string) (*models.PaymentMethod, error) {
	// For now, return nil - this would normally query the payment service
	r.Logger.WithField("payment_method_id", id).Info("Finding payment method by ID")
	return nil, fmt.Errorf("not implemented: FindPaymentMethodByID - findPaymentMethodByID")
}

// FindRefundByID is the resolver for the findRefundByID field.
func (r *entityResolver) FindRefundByID(ctx context.Context, id string) (*models.Refund, error) {
	// For now, return nil - this would normally query the payment service
	r.Logger.WithField("refund_id", id).Info("Finding refund by ID")
	return nil, fmt.Errorf("not implemented: FindRefundByID - findRefundByID")
}

// FindTransactionByID is the resolver for the findTransactionByID field.
func (r *entityResolver) FindTransactionByID(ctx context.Context, id string) (*models.Transaction, error) {
	// For now, return nil - this would normally query the payment service
	r.Logger.WithField("transaction_id", id).Info("Finding transaction by ID")
	return nil, fmt.Errorf("not implemented: FindTransactionByID - findTransactionByID")
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *entityResolver) FindAddressByID(ctx context.Context, id string) (*models.Address, error) {
	panic(fmt.Errorf("not implemented: FindAddressByID - findAddressByID"))
}
*/
