// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/99designs/gqlgen/plugin/federation/fedruntime"
)

var (
	ErrUnknownType  = errors.New("unknown type")
	ErrTypeNotFound = errors.New("type not found")
)

func (ec *executionContext) __resolve__service(ctx context.Context) (fedruntime.Service, error) {
	if ec.DisableIntrospection {
		return fedruntime.Service{}, errors.New("federated introspection disabled")
	}

	var sdl []string

	for _, src := range sources {
		if src.BuiltIn {
			continue
		}
		sdl = append(sdl, src.Input)
	}

	return fedruntime.Service{
		SDL: strings.Join(sdl, "\n"),
	}, nil
}

func (ec *executionContext) __resolve_entities(ctx context.Context, representations []map[string]interface{}) []fedruntime.Entity {
	list := make([]fedruntime.Entity, len(representations))

	repsMap := map[string]struct {
		i []int
		r []map[string]interface{}
	}{}

	// We group entities by typename so that we can parallelize their resolution.
	// This is particularly helpful when there are entity groups in multi mode.
	buildRepresentationGroups := func(reps []map[string]interface{}) {
		for i, rep := range reps {
			typeName, ok := rep["__typename"].(string)
			if !ok {
				// If there is no __typename, we just skip the representation;
				// we just won't be resolving these unknown types.
				ec.Error(ctx, errors.New("__typename must be an existing string"))
				continue
			}

			_r := repsMap[typeName]
			_r.i = append(_r.i, i)
			_r.r = append(_r.r, rep)
			repsMap[typeName] = _r
		}
	}

	isMulti := func(typeName string) bool {
		switch typeName {
		default:
			return false
		}
	}

	resolveEntity := func(ctx context.Context, typeName string, rep map[string]interface{}, idx []int, i int) (err error) {
		// we need to do our own panic handling, because we may be called in a
		// goroutine, where the usual panic handling can't catch us
		defer func() {
			if r := recover(); r != nil {
				err = ec.Recover(ctx, r)
			}
		}()

		switch typeName {
		case "Address":
			resolverName, err := entityResolverNameForAddress(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Address": %w`, err)
			}
			switch resolverName {

			case "findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode":
				id0, err := ec.unmarshalOString2string(ctx, rep["firstName"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id1, err := ec.unmarshalOString2string(ctx, rep["lastName"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 1 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id2, err := ec.unmarshalOString2string(ctx, rep["street1"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 2 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id3, err := ec.unmarshalOString2string(ctx, rep["street2"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 3 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id4, err := ec.unmarshalOString2string(ctx, rep["city"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 4 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id5, err := ec.unmarshalOString2string(ctx, rep["state"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 5 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id6, err := ec.unmarshalOString2string(ctx, rep["country"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 6 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				id7, err := ec.unmarshalOString2string(ctx, rep["postalCode"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 7 for findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode(ctx, &id0, &id1, &id2, &id3, &id4, &id5, &id6, &id7)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Address": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "Payment":
			resolverName, err := entityResolverNameForPayment(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Payment": %w`, err)
			}
			switch resolverName {

			case "findPaymentByID":
				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPaymentByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPaymentByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Payment": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "PaymentMethod":
			resolverName, err := entityResolverNameForPaymentMethod(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "PaymentMethod": %w`, err)
			}
			switch resolverName {

			case "findPaymentMethodByID":
				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findPaymentMethodByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindPaymentMethodByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "PaymentMethod": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "Refund":
			resolverName, err := entityResolverNameForRefund(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Refund": %w`, err)
			}
			switch resolverName {

			case "findRefundByID":
				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findRefundByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindRefundByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Refund": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}
		case "Transaction":
			resolverName, err := entityResolverNameForTransaction(ctx, rep)
			if err != nil {
				return fmt.Errorf(`finding resolver for Entity "Transaction": %w`, err)
			}
			switch resolverName {

			case "findTransactionByID":
				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
				if err != nil {
					return fmt.Errorf(`unmarshalling param 0 for findTransactionByID(): %w`, err)
				}
				entity, err := ec.resolvers.Entity().FindTransactionByID(ctx, id0)
				if err != nil {
					return fmt.Errorf(`resolving Entity "Transaction": %w`, err)
				}

				list[idx[i]] = entity
				return nil
			}

		}
		return fmt.Errorf("%w: %s", ErrUnknownType, typeName)
	}

	resolveManyEntities := func(ctx context.Context, typeName string, reps []map[string]interface{}, idx []int) (err error) {
		// we need to do our own panic handling, because we may be called in a
		// goroutine, where the usual panic handling can't catch us
		defer func() {
			if r := recover(); r != nil {
				err = ec.Recover(ctx, r)
			}
		}()

		switch typeName {

		default:
			return errors.New("unknown type: " + typeName)
		}
	}

	resolveEntityGroup := func(typeName string, reps []map[string]interface{}, idx []int) {
		if isMulti(typeName) {
			err := resolveManyEntities(ctx, typeName, reps, idx)
			if err != nil {
				ec.Error(ctx, err)
			}
		} else {
			// if there are multiple entities to resolve, parallelize (similar to
			// graphql.FieldSet.Dispatch)
			var e sync.WaitGroup
			e.Add(len(reps))
			for i, rep := range reps {
				i, rep := i, rep
				go func(i int, rep map[string]interface{}) {
					err := resolveEntity(ctx, typeName, rep, idx, i)
					if err != nil {
						ec.Error(ctx, err)
					}
					e.Done()
				}(i, rep)
			}
			e.Wait()
		}
	}
	buildRepresentationGroups(representations)

	switch len(repsMap) {
	case 0:
		return list
	case 1:
		for typeName, reps := range repsMap {
			resolveEntityGroup(typeName, reps.r, reps.i)
		}
		return list
	default:
		var g sync.WaitGroup
		g.Add(len(repsMap))
		for typeName, reps := range repsMap {
			go func(typeName string, reps []map[string]interface{}, idx []int) {
				resolveEntityGroup(typeName, reps, idx)
				g.Done()
			}(typeName, reps.r, reps.i)
		}
		g.Wait()
		return list
	}
}

func entityResolverNameForAddress(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m   map[string]interface{}
			val interface{}
			ok  bool
		)
		_ = val
		m = rep
		if _, ok = m["firstName"]; !ok {
			break
		}
		m = rep
		if _, ok = m["lastName"]; !ok {
			break
		}
		m = rep
		if _, ok = m["street1"]; !ok {
			break
		}
		m = rep
		if _, ok = m["street2"]; !ok {
			break
		}
		m = rep
		if _, ok = m["city"]; !ok {
			break
		}
		m = rep
		if _, ok = m["state"]; !ok {
			break
		}
		m = rep
		if _, ok = m["country"]; !ok {
			break
		}
		m = rep
		if _, ok = m["postalCode"]; !ok {
			break
		}
		return "findAddressByFirstNameAndLastNameAndStreet1AndStreet2AndCityAndStateAndCountryAndPostalCode", nil
	}
	return "", fmt.Errorf("%w for Address", ErrTypeNotFound)
}

func entityResolverNameForPayment(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m   map[string]interface{}
			val interface{}
			ok  bool
		)
		_ = val
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPaymentByID", nil
	}
	return "", fmt.Errorf("%w for Payment", ErrTypeNotFound)
}

func entityResolverNameForPaymentMethod(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m   map[string]interface{}
			val interface{}
			ok  bool
		)
		_ = val
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findPaymentMethodByID", nil
	}
	return "", fmt.Errorf("%w for PaymentMethod", ErrTypeNotFound)
}

func entityResolverNameForRefund(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m   map[string]interface{}
			val interface{}
			ok  bool
		)
		_ = val
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findRefundByID", nil
	}
	return "", fmt.Errorf("%w for Refund", ErrTypeNotFound)
}

func entityResolverNameForTransaction(ctx context.Context, rep map[string]interface{}) (string, error) {
	for {
		var (
			m   map[string]interface{}
			val interface{}
			ok  bool
		)
		_ = val
		m = rep
		if _, ok = m["id"]; !ok {
			break
		}
		return "findTransactionByID", nil
	}
	return "", fmt.Errorf("%w for Transaction", ErrTypeNotFound)
}
