// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateMerchantInput struct {
	BusinessName string  `json:"businessName"`
	BusinessType *string `json:"businessType,omitempty"`
	TaxID        *string `json:"taxId,omitempty"`
	ContactEmail string  `json:"contactEmail"`
	ContactPhone *string `json:"contactPhone,omitempty"`
	Website      *string `json:"website,omitempty"`
	Description  *string `json:"description,omitempty"`
	Settings     *string `json:"settings,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateMerchantInput struct {
	BusinessName       *string `json:"businessName,omitempty"`
	BusinessType       *string `json:"businessType,omitempty"`
	TaxID              *string `json:"taxId,omitempty"`
	ContactEmail       *string `json:"contactEmail,omitempty"`
	ContactPhone       *string `json:"contactPhone,omitempty"`
	Website            *string `json:"website,omitempty"`
	Description        *string `json:"description,omitempty"`
	IsActive           *bool   `json:"isActive,omitempty"`
	Settings           *string `json:"settings,omitempty"`
	VerificationStatus *string `json:"verificationStatus,omitempty"`
}
