apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: unified-commerce
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: unified-commerce/identity-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: IDENTITY_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: JWT_SECRET
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: unified-commerce
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-account-service
  namespace: unified-commerce
  labels:
    app: merchant-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-account-service
  template:
    metadata:
      labels:
        app: merchant-account-service
    spec:
      containers:
      - name: merchant-account-service
        image: unified-commerce/merchant-account-service:latest
        ports:
        - containerPort: 8008
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: MERCHANT_ACCOUNT_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: JWT_SECRET
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-account-service
  namespace: unified-commerce
spec:
  selector:
    app: merchant-account-service
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  namespace: unified-commerce
  labels:
    app: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
      - name: product-catalog-service
        image: unified-commerce/product-catalog-service:latest
        ports:
        - containerPort: 8006
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: PRODUCT_CATALOG_SERVICE_PORT
        - name: DATABASE_URL
          value: mongodb://mongodb:$(MONGO_INITDB_ROOT_PASSWORD)@mongodb:27017/product_catalog?authSource=admin
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: unified-commerce
spec:
  selector:
    app: product-catalog-service
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: unified-commerce
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: unified-commerce/inventory-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: INVENTORY_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: unified-commerce
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: unified-commerce
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: unified-commerce/order-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ORDER_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: KAFKA_BROKERS
          value: kafka:9092
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: unified-commerce
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: unified-commerce
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: unified-commerce/cart-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: CART_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: unified-commerce
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: unified-commerce
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: unified-commerce/payment-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: PAYMENT_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: KAFKA_BROKERS
          value: kafka:9092
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: STRIPE_SECRET_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: unified-commerce
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotions-service
  namespace: unified-commerce
  labels:
    app: promotions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotions-service
  template:
    metadata:
      labels:
        app: promotions-service
    spec:
      containers:
      - name: promotions-service
        image: unified-commerce/promotions-service:latest
        ports:
        - containerPort: 8007
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: PROMOTIONS_SERVICE_PORT
        - name: DATABASE_URL
          value: postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/unified_commerce?sslmode=disable
        - name: REDIS_URL
          value: redis://:$(REDIS_PASSWORD)@redis:6379/0
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: unified-commerce-config
              key: ENVIRONMENT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unified-commerce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: promotions-service
  namespace: unified-commerce
spec:
  selector:
    app: promotions-service
  ports:
    - protocol: TCP
      port: 8007
      targetPort: 8007
  type: ClusterIP