package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"unified-commerce/services/identity/models"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*models.User, error) {
	// Use the same service method as the user query resolver
	user, err := r.IdentityService.GetUserByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to find user by ID %s: %w", id, err)
	}
	return user, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
