// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"unified-commerce/services/identity/models"
)

type AuthPayload struct {
	User         *models.User `json:"user"`
	AccessToken  string       `json:"accessToken"`
	RefreshToken string       `json:"refreshToken"`
	ExpiresIn    int          `json:"expiresIn"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreatePermissionInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateRoleInput struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	PermissionIds []string `json:"permissionIds,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     *string `json:"phone,omitempty"`
}

type UpdatePermissionInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateRoleInput struct {
	Name          *string  `json:"name,omitempty"`
	Description   *string  `json:"description,omitempty"`
	PermissionIds []string `json:"permissionIds,omitempty"`
}

type UpdateUserInput struct {
	Email     *string  `json:"email,omitempty"`
	Username  *string  `json:"username,omitempty"`
	FirstName *string  `json:"firstName,omitempty"`
	LastName  *string  `json:"lastName,omitempty"`
	IsActive  *bool    `json:"isActive,omitempty"`
	RoleIds   []string `json:"roleIds,omitempty"`
}
